apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
    - name: app-name
      type: string
      description: The name of the application
    - name: namespace
      type: string
      description: The namespace to deploy to
      default: default
  tasks:
    # This is a simplified task that just echoes what it would do
    - name: simulated-deploy
      taskSpec:
        steps:
        - name: echo-deploy
          image: alpine:3.15.1
          script: |
            echo "Would deploy $(params.app-name) to $(params.namespace)..."
            echo "This is just a simulation for testing the template resolver."
    
    # Post-dev deployment tasks
    {{- if .PostDevSteps}}
    # Start of user-defined post-dev steps
    {{.PostDevSteps}}
    # End of user-defined post-dev steps
    {{- else}}
    # Default post-dev steps
    - name: default-dev-checks
      runAfter:
        - simulated-deploy
      taskSpec:
        steps:
        - name: echo
          image: alpine:3.15.1
          script: |
            echo "Running default post-dev checks for $(params.app-name)..."
            echo "No custom post-dev steps were provided, using defaults."
    {{- end}}
    
    # Post-prod deployment tasks
    {{- if .PostProdSteps}}
    # Start of user-defined post-prod steps
    {{.PostProdSteps}}
    # End of user-defined post-prod steps
    {{- else}}
    # Default post-prod steps
    - name: default-prod-checks
      runAfter:
        - simulated-deploy
      taskSpec:
        steps:
        - name: echo
          image: alpine:3.15.1
          script: |
            echo "Running default post-prod checks for $(params.app-name)..."
            echo "No custom post-prod steps were provided, using defaults."
    {{- end}}
    
    # Simple notification task
    - name: notify
      runAfter:
      - simulated-deploy
      taskSpec:
        steps:
        - name: echo-notify
          image: alpine:3.15.1
          script: |
            echo "Simulated notification: Deployed $(params.app-name) to $(params.namespace)"