apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deployment-pipeline
spec:
  params:
    - name: app-name
      type: string
      description: The name of the application
    - name: image-name
      type: string
      description: The container image name
    - name: namespace
      type: string
      description: The namespace to deploy to
      default: default
    - name: environment
      type: string
      description: The deployment environment (dev or prod)
      default: dev
  tasks:
    - name: deploy
      taskRef:
        name: kubernetes-actions
      params:
        - name: script
          value: |
            kubectl apply -f k8s/$(params.environment)/deployment.yaml -n $(params.namespace)
            kubectl rollout status deployment/$(params.app-name) -n $(params.namespace)
    
    # Post-dev deployment tasks
    {{- if .PostDevSteps}}
    # Start of user-defined post-dev steps
    {{.PostDevSteps}}
    # End of user-defined post-dev steps
    {{- else}}
    # Default post-dev steps (simplified inline task)
    - name: default-dev-checks
      runAfter:
        - deploy
      taskSpec:
        steps:
        - name: echo
          image: alpine:3.15.1
          script: |
            echo "No post-dev validation steps defined. Proceeding."
    {{- end}}
    
    # Post-prod deployment tasks
    {{- if .PostProdSteps}}
    # Start of user-defined post-prod steps
    {{.PostProdSteps}}
    # End of user-defined post-prod steps
    {{- else}}
    # Default post-prod steps (simplified inline task)
    - name: default-prod-checks
      runAfter:
        - deploy
      taskSpec:
        steps:
        - name: echo
          image: alpine:3.15.1
          script: |
            echo "No post-prod validation steps defined. Proceeding."
    {{- end}}
    
    - name: notify-slack
      taskRef:
        name: slack-notification
      runAfter:
        - deploy
      params:
        - name: message
          value: "Deployed $(params.app-name) to $(params.environment)"
        - name: channel
          value: "#deployments"