apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
    - name: app-name
      type: string
      description: The name of the application
    - name: namespace
      type: string
      description: The namespace to deploy to
      default: default
  tasks:
    # This is a simplified task that just echoes what it would do
    - name: simulated-deploy
      taskSpec:
        steps:
        - name: echo-deploy
          image: alpine:3.15.1
          script: |
            echo "Would deploy $(params.app-name) to $(params.namespace)..."
            echo "This is just a simulation for testing the template resolver."
    
    # Post-dev deployment tasks
    {{- if .PostDevSteps}}
    # User-defined post-dev steps
    {{.PostDevSteps}}
    {{- else}}
    # Default post-dev step
    - name: default-dev-validation
      runAfter:
        - simulated-deploy
      taskSpec:
        steps:
        - name: echo
          image: alpine:3.15.1
          script: |
            echo "No post-dev validation steps defined. Proceeding."
    {{- end}}
    
    # Post-prod deployment tasks
    {{- if .PostProdSteps}}
    # User-defined post-prod steps
    {{.PostProdSteps}}
    {{- else}}
    # Default post-prod step
    - name: default-prod-validation
      runAfter:
        - simulated-deploy
      taskSpec:
        steps:
        - name: echo
          image: alpine:3.15.1
          script: |
            echo "No post-prod validation steps defined. Proceeding."
    {{- end}}
    
    # Simple notification task
    - name: notify
      runAfter:
        - simulated-deploy
      taskSpec:
        steps:
        - name: echo-notify
          image: alpine:3.15.1
          script: |
            echo "Simulated notification: Deployed $(params.app-name) to $(params.namespace)"