apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-resolver
  namespace: tekton-pipelines-resolvers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-resolver
      resolution.tekton.dev/type: template
  template:
    metadata:
      labels:
        app: template-resolver
        resolution.tekton.dev/type: template
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: template-resolver
              topologyKey: kubernetes.io/hostname
            weight: 100
      serviceAccountName: tekton-pipelines-resolvers
      containers:
      - name: controller
        image: kind.local/template-resolver-96634542ebcc71fd14f04f28d0789c48:abae354bdd719d57396852c708ad0b69e765d2d13adaea93af7515b5b9a947ac
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - name: metrics
          containerPort: 9090
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: tekton.dev/resolution
        - name: GIT_SSH_COMMAND
          value: "ssh -i /etc/git-secrets/ssh-privatekey -o StrictHostKeyChecking=no"
        volumeMounts:
        - name: git-ssh-key
          mountPath: /etc/git-secrets
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      volumes:
      - name: git-ssh-key
        secret:
          secretName: git-ssh-key
          defaultMode: 0400
          optional: true