apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-resolver
  namespace: tekton-pipelines-resolvers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-resolver
      resolution.tekton.dev/type: template
  template:
    metadata:
      labels:
        app: template-resolver
        resolution.tekton.dev/type: template
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: template-resolver
              topologyKey: kubernetes.io/hostname
            weight: 100
      serviceAccountName: tekton-pipelines-resolvers
      containers:
      - name: controller
        image: kind.local/template-resolver-96634542ebcc71fd14f04f28d0789c48:e35a6c9c5e2841ea1183ce6719f33db4970f2b80096c8e9b7f93208658e5ab61
        args:
        - "-v=9"  # Enable debug logging
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - name: metrics
          containerPort: 9090
        env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: tekton.dev/resolution
        # Git configuration
        - name: GIT_SSH_COMMAND
          value: "ssh -i /etc/git-secrets/ssh-privatekey -o StrictHostKeyChecking=no"
        - name: GIT_CLONE_DEPTH
          value: "1"
        - name: GIT_DEFAULT_BRANCH
          value: "main"
        
        # Resolver configuration
        - name: DEBUG
          value: "true"
        - name: RESOLUTION_TIMEOUT
          value: "10m"
        - name: HTTP_TIMEOUT
          value: "60s"
        volumeMounts:
        - name: git-ssh-key
          mountPath: /etc/git-secrets
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
      volumes:
      - name: git-ssh-key
        secret:
          secretName: git-ssh-key
          defaultMode: 0400
          optional: true
