apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: direct-simple-pipeline
spec:
  params:
    - name: app-name
      type: string
      description: The name of the application
    - name: namespace
      type: string
      description: The namespace to deploy to
      default: default
  tasks:
    # This is a simplified task that just echoes what it would do for dev
    - name: simulated-dev-deploy
      taskSpec:
        steps:
        - name: echo-deploy
          image: alpine:3.15.1
          script: |
            echo "Would deploy $(params.app-name) to dev environment in $(params.namespace)..."
            echo "This is just a simulation for testing the template resolver."
    
    # Post-dev deployment tasks
    - name: run-integration-tests
      runAfter:
        - simulated-dev-deploy
      taskSpec:
        steps:
        - name: echo-test
          image: alpine:3.15.1
          script: |
            echo "Running integration tests for $(params.app-name)..."
            echo "Test suite: smoke"
            echo "App URL: https://$(params.app-name).dev.example.com"
            echo "Test completed successfully!"
    
    # Production deployment - depends on successful dev tests
    - name: simulated-prod-deploy
      runAfter:
        - run-integration-tests
      taskSpec:
        steps:
        - name: echo-deploy
          image: alpine:3.15.1
          script: |
            echo "Would deploy $(params.app-name) to production environment in $(params.namespace)..."
            echo "Note: This only runs after successful dev tests!"
            echo "This is just a simulation for testing the template resolver."
    
    # Post-prod deployment tasks
    - name: verify-deployment
      runAfter:
        - simulated-prod-deploy
      taskSpec:
        steps:
        - name: echo-verify
          image: alpine:3.15.1
          script: |
            echo "Verifying production deployment of $(params.app-name)..."
            echo "Checking endpoint: /health"
            echo "Timeout: 300s"
            echo "Verification completed successfully!"
    
    # Simple notification task
    - name: notify
      runAfter:
        - verify-deployment
      taskSpec:
        steps:
        - name: echo-notify
          image: alpine:3.15.1
          script: |
            echo "Simulated notification: Deployed $(params.app-name) to dev and prod environments in $(params.namespace)"
            echo "All validation steps completed successfully."