apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: direct-pipeline-run
spec:
  pipelineRef:
    name: direct-simple-pipeline
  params:
    - name: app-name
      value: direct-example-app
    - name: namespace
      value: default
  timeouts:
    pipeline: "10m"