apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: example-app-deployment
spec:
  pipelineRef:
    resolver: template
    params:
      - name: repository
        value: https://github.com/thrivemarket/tekton-template-resolver
      - name: path
        value: examples/templates/simple.yaml
      - name: post-dev-steps
        value: |
          - name: run-integration-tests
            runAfter:
              - simulated-dev-deploy
            taskSpec:
              steps:
              - name: echo-test
                image: alpine:3.15.1
                script: |
                  echo "Running integration tests for $(params.app-name)..."
                  echo "Test suite: smoke"
                  echo "Timeout: 120s"
                  echo "App URL: https://$(params.app-name).dev.example.com"
                  echo "Test completed successfully!"
      - name: post-prod-steps
        value: |
          - name: verify-deployment
            runAfter:
              - simulated-prod-deploy
            taskSpec:
              steps:
              - name: echo-verify
                image: alpine:3.15.1
                script: |
                  echo "Verifying production deployment of $(params.app-name)..."
                  echo "Timeout: 300s"
                  echo "Running health checks..."
                  echo "Verification completed successfully!"
          - name: notify-security-team
            runAfter:
              - verify-deployment
            taskSpec:
              steps:
              - name: echo-notify
                image: alpine:3.15.1
                script: |
                  echo "Sending notification to security team..."
                  echo "Recipients: security@example.com"
                  echo "Subject: New production deployment completed"
                  echo "Email sent successfully!"
  params:
    - name: app-name
      value: example-app
    - name: git-url
      value: https://github.com/example/example-app
    - name: image-name
      value: example.com/example-app:latest
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
